export const GET_GENRE_API = '/genre/movie/list'
export const GET_MOVIE_GENRE_API = '/discover/movie/'
export const MOVIE_IMAGE = 'https://image.tmdb.org/t/p/original/'
export const AUTH_GET_REQ_TOKEN = '/authentication/token/new'
export const AUTH_VALIDATE_LOGIN = '/authentication/token/validate_with_login'
export const AUTH_GET_SESSION_TOKEN = '/authentication/session/new'
export const GET_MOVIE_TRENDING_API = '/trending/movie/'